version: '3.7'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - backend

  backend:
    image: toroinvest/quotesmock
    ports: 
      - 8080:8080